name = "psu_ada_gameengine"
description = ""
version = "0.1.0"
authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = [ "component_table_test",
                  "ecs_systems_test", 
                  "ecs_store_test", 
                  "ecs_integration_test",
                  "arkanoid_ecs_test"   ]

[[depends-on]]
qoi = "~0.1.0"

[[actions]]
type = "post-build"
command = ["gprbuild", "-P", "psu_ada_gameengine_tests.gpr"]

[[actions]]
type = "test"
command = ["bin/component_table_test"]

[[actions]]
type = "test"
command = ["bin/ecs_systems_test"]

[[actions]]
type = "test"
command = ["bin/ecs_store_test"]

[[actions]]
type = "test"
command = ["bin/ecs_integration_test"]

[[actions]]
type = "test"
command = ["bin/arkanoid_ecs_test"]